language: java
jdk:
  - oraclejdk8
sudo: required
before_script:
  # Install Siegfried
  - curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
  - echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install siegfried -y
  # Install Clam Anti Virus
  - sudo apt-get install clamav -y
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update 
  - sudo apt-get install -y ffmpeg
  - sudo apt-get install -y imagemagick
  - sudo apt-get install -y sox
  - sudo apt-get install -y unoconv
  - sudo apt-get install -y ghostscript
  - sudo apt-get install -y mencoder
