language: java
jdk:
- oraclejdk8
sudo: required
install: true
env:
  - MAVEN_OPTS="-Xmx4g -Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m -XX:PermSize=512m"
addons:
  sonarqube:
    organization: "keeps"
    token:
      secure: "On53R35PWhHE5kJZophSGhiyfU3w/df/TgdVObsw1N64LGaGXiQQxaYuaYRTYT34SQHuZPRqpV84L8QMW5WGDEwH3EhaN3I3on1w6djrQ4lqk0+2yrqHtKkhL5+hByC50UQcdLoX84q6Ri6A570/tpNhT+/GnT2+1deJ5C+fjiU="
    branches:
      - master
      - development
before_script:
- curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
- echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get -qq update
- sudo apt-get -qq install siegfried -y
- sudo sf -update
- sudo apt-get -qq install clamav clamav-daemon -y
- sudo freshclam
#before_install:
#  - sudo rm /etc/mavenrc
#  - export M2_HOME=/usr/local/maven
#  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m -XX:PermSize=512m"
script: mvn -Dtestng.groups="travis" -Denforcer.skip=true clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.sonar/cache
notifications:
  slack:
    secure: Hg2xvznD2QGhbCHRXN9DFM6dYIfeiZStj0Ud+OBS2swX9YOM77ufbDkMWF/yAAwxNg45QIC3a3okVy6TLzY5hA/PSKlc/5/ClujgRy02HLXlbYZ9psQH22/VFrER3uFkIpvMPhrxh3NLo/UMWfwvmwq26ziFnW4W6UDn/XXCHPE=
after_success:
  - bash <(curl -s https://codecov.io/bash)
