language: java
jdk:
  - oraclejdk8
sudo: required
before_script:
  # Install Siegfried
  - curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
  - echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install siegfried -y
  # Install Clam Anti Virus
  - sudo apt-get install clamav -y
  # Install Avconv
  - sudo apt-get install libav-tools -y
  # Install ImageMagick
  - sudo apt-get install imagemagick -y
  # Install SoX
  - sudo apt-get install sox libsox-fmt-all -y
  # Install Unoconv
  - sudo apt-get install unoconv -y
  # Install GhostScript
  - sudo apt-get install ghostscript libgs-dev -y
